export const SecondStepFields = [
    {
        type: 'DICTI',
        label: 'Страна',
        name: 'country',
        required: true,
        span: 12,
        dicti: [
            { value: 'RU', label: 'Россия' },
            { value: 'KZ', label: 'Казахстан' },
            { value: 'BY', label: 'Беларусь' },
            { value: 'UZ', label: 'Узбекистан' },
            { value: 'UA', label: 'Украина' },
            { value: 'KG', label: 'Киргизия' },
            { value: 'AM', label: 'Армения' },
            { value: 'AZ', label: 'Азербайджан' },
            { value: 'TJ', label: 'Таджикистан' },
            { value: 'MD', label: 'Молдова' },
        ],
    },
    {
        type: 'TEXT',
        label: 'Город',
        name: 'city',
        required: true,
        span: 12,
    },
    {
        type: 'TEXT',
        label: 'Улица',
        name: 'street',
        required: true,
        span: 12,
    },
    {
        type: 'NUMBER',
        label: 'Почтовый индекс',
        name: 'mail_index',
        required: true,
        minLength: 5,
        maxLength: 10,
        span: 12,
    },
]
